### ISSUE TITLE
Default sort uses value, not text for columns where type = select

### ISSUE THREAD

**Issue by matthew-james** [onijim/owl-table#66]
Reproduction steps:
-set this in options:
    sort : {column : 'course_id',order : 'asc'}
-set column course_id to type: select
-set numeric 'value' values and text 'text' values for the select options.

expected output:
-when the page loads the records should be sorted alphabetically by the text value for course_id

actual output:
-when the page loads the records are sorted numerically by the values.

*note that sorting alphabetically for the course_id works perfectly when clicking the column header to sort.

**Comment by onijim** [comment]
Default sorting should now work, on develop

It should also keep the sort whenever your data changes now...
