### ISSUE TITLE
checkboxes always render as checked

### ISSUE THREAD

**Issue by matthew-james** [onijim/owl-table#68]
Checkboxes always render as checked.  The unclicked state renders correctly and the correct value is sent to the server.

Expected output:

The checkbox should render as unchecked if the value is false.

![cb_unclicked](https://cloud.githubusercontent.com/assets/9440455/5569289/b4c13b84-8f3b-11e4-922f-c41c06d4e548.png)
![cb_clicked](https://cloud.githubusercontent.com/assets/9440455/5569290/b7178a32-8f3b-11e4-8cdc-6fda68dfe04f.png)

**Comment by onijim** [comment]
Should be resolved on develop, assuming 'Y' is indeed the valid 'true' value here
