### ISSUE TITLE
parent record uses child record data

### ISSUE THREAD

**Issue by matthew-james** [onijim/owl-table#69]
when setting parent/child records with the same name for parent and child fields, the parent value is set to the child value.

![linked_section_screenshot](https://cloud.githubusercontent.com/assets/9440455/5573684/53697e9e-8f7e-11e4-92b2-9547c1256370.png)

data:
https://gist.github.com/matthew-james/30352781fa900989fbd6
fields:
https://gist.github.com/matthew-james/aeaa5a8436cbcacc0778

**Comment by lainceline** [comment]
Fixed on develop...there was a block of code causing this to happen and I can't remember what its original purpose was.  I took it out and nothing seems to have changed other than this bug being fixed.
