### ISSUE TITLE
customize columns shows strikeout for visible true after reloading data

### ISSUE THREAD

**Issue by matthew-james** [onijim/owl-table#71]
reproduction steps:
load a page w/ a column set to visible: false.  it works as expected.
reload the column data w/ ajax.
click the customize columns button.
all of the columns are shown striked out, even thou only 1 column is set to visible : false

![screen shot 2015-01-08 at 12 01 43 pm](https://cloud.githubusercontent.com/assets/9440455/5666592/ac502820-972e-11e4-8943-1103f8ef2509.png)

**Comment by onijim** [comment]
Fixed on develop and in v0.1.7
