### ISSUE TITLE
numbers only tooltip doesnt clear

### ISSUE THREAD

**Issue by matt-allan** [onijim/owl-table#73]
click to edit a number field
click outside of the field to finish editing, without changing the value
the tooltip persists

![1](https://cloud.githubusercontent.com/assets/9440455/5683863/6b2c7f3a-97f9-11e4-99f4-c6e189b871cc.png)

![2](https://cloud.githubusercontent.com/assets/9440455/5683865/6e73c694-97f9-11e4-8651-672a9a506d34.png)

![3](https://cloud.githubusercontent.com/assets/9440455/5683869/73c5d8b2-97f9-11e4-8bb4-dfcc9208731b.png)

**Comment by lainceline** [comment]
Resolved in cf498d07740712afd105f1242a33903949ad19b1
