### ISSUE TITLE
checked checkboxes default to unchecked

### ISSUE THREAD

**Issue by matt-allan** [onijim/owl-table#74]
load a record
--one column should be type checkbox
--that record should have value = true for the checkbox column
the checkbox displays a green checkmark which is correct
clicking the checkmark creates an unchecked checkbox

expected output:
the checkbox should default to checked

![1](https://cloud.githubusercontent.com/assets/9440455/5683940/0fa1dfec-97fa-11e4-8eec-35742a496839.png)

![2](https://cloud.githubusercontent.com/assets/9440455/5683942/13194f48-97fa-11e4-9a37-4532dc7e1496.png)

**Comment by lainceline** [comment]
Should be fixed on develop now.
